config/routes.rb
Rails.application.routes.draw do
  resources :dogs, only: [:index, :show]
  resources :posts, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  after_create :create_inverse_relationship

  belongs_to :friend1, class_name: 'Dog'
  belongs_to :friend2, class_name: 'Dog'

  validates :friend1, presence: true
  validates :friend2, presence: true, uniqueness: { scope: :friend1 }
  validate :not_self

  private

  def create_inverse_relationship
    friend2.friendships.create!(friend2: friend1) unless Buddy.find_by(friend1: self.friend2, friend2: self.friend1)
  end

  def not_self
    errors.add(:friend2, "can't be friends with yourself!") if friend1 == friend2
  end

end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :friendships, class_name: "Buddy", foreign_key: "friend1_id"
  has_many :buddies, through: :friendships, source: :friend2

  has_many :posts

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :dog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :find_dog, only: [:show]

  def index
    @dogs = Dog.all
  end

  def show
    @post = Post.new
  end
  
  private

  def find_dog
    @dog = Dog.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show]

  def index
    @posts = Post.all
  end
  
  private

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dogs/index.html.erb
<ul>
  <% @dogs.each do |dog| %>
    <li>
      <%= link_to dog.name, dog %>
    </li>
  <% end %>
</ul>

app/views/dogs/show.html.erb
<div class="main-container">

  <div id="main-info">
    <img src=<%= @dog.image_url %>  alt=<%= @dog.name %> />
    <h2> <%= @dog.name %> </h2>
    <h3> <%= @dog.catchphrase %> </h3>
  </div>


  <h3>Friends</h3>
  <ul class="buddies-container">

    <% @dog.buddies.each do |buddy| %>
    <li class="buddy">
      <img src=<%= buddy.image_url %>  alt=<%= buddy.name %> />
      <span class="buddy-link"><%= link_to buddy.name, buddy %></span>
    </li>
    <% end %>

  </ul>

</div>


<aside class="sidebar">

  <ul class="posts-container">
    <h3>Posts</h3>

    <% @dog.posts.each do |post| %>
    <li class="post-link">
      <%= link_to post.title, post %>
    </li>
    <% end %>
  </ul>

  <%= form_for @post, html: {id: "new-form"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :body %>
    <%= f.text_area :body %>
    <%= f.submit "Make a new post!", disabled: true %>
  <% end %>

</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <h1>DogBook🐕</h1>
      <div class="ui two item menu dog" >
        <%= link_to "All Doggies", dogs_path, class: "item" %>
        <%= link_to "All Posts", posts_path, class: "item" %>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post %>
    </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<div class="post">
  <div class="post-header">
    <h2> <%= @post.title %> </h2>
    <p> <%= @post.body %> </p>
  <div>

  <p class="post-content">
    By: <%= link_to @post.dog.name, @post.dog %>
    <span>
      Created on: <%= @post.created_at.strftime("%I:%M%p, %m/%d/%Y") %>
    </span>
  </p>
</div>